# Site settings
title: Liyong's Blog
SEOTitle: 一个神奇的网站
header-img: img/index.jpg
email: 2321591758@qq.com
description: "生命短暂,珍惜身边的每一个人"
keyword: "java, 数据库, 前端, 动漫, 游戏(王者荣耀,吃鸡), 运动, 旅行"
url: "https://cholechow1.github.io"         # your host, for absolute UR
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/CholeChow1/CholeChow1.github.io.git"
# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一个平凡的人却有着大大的梦"
sidebar-avatar: /img/about-Otone.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     6056675330
zhihu_username:     li-yong-ji-suan-ji
github_username:    CholeChow1
facebook_username:  李勇
jianshu_username:  6c1284ced65e
#twitter_username:   




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com
# disqus_username: liyong

# Gitalk
gitalk:
  enable: true  #是否开启Gitalk评论
  clientID: 7e7ca0f24e79641b2d24                            #生成的clientID
  clientSecret: a8cdb2aa09ad6f4a24903790ea9ba03cc302d4a1   #生成的clientSecret
  repo: CholeChow1.github.io    #仓库名称
  owner: CholeChow1    #github用户名
  admin: CholeChow1
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-130240864-1'            # Format: UA-xxxxxx-xx
ga_domain: auto




# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0             # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# links
links: [
    {
        title: "个人のGitHub",
        href: "https://github.com/CholeChow1"
    },{
        title: "简书·Liyong",
        href: "https://www.jianshu.com/u/6c1284ced65e"
    },{
        title: "个人のbilibili",
        href: "space.bilibili.com/105316984?spm_id_from=333.33.b_73656375726974794f75744c696e6b.1"
    },{
        title: "CSDN.liyong",
        href: "https://me.csdn.net/java__liyong"
    },{
        title: "知乎.liyong",
        href: "https://www.zhihu.com/people/li-yong-ji-suan-ji/activities"
    }
]
